version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: hoon-mysql
    ports:
      - "23308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    volumes:
      - ./data/mysql/:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: hoon-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/:/data


networks:
  default:
    driver: bridge